//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTful1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class contacte
    {
        [JsonIgnore]
        public bool serializeMail = false;
        [JsonIgnore]
        public bool serializeTelefons = false;
        public bool ShouldSerializeemails() {

            return serializeMail;

        }
        public bool ShouldSerializetelefons() {

            return serializeTelefons;

        }

    }
}
